name: GitHub Actions

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  Test-React-App:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run eslint

      - name: Run truffle compile
        run: npm run truffle compile

      - name: Run truffle migrate
        run: npm run truffle migrate

      - name: Run truffle test
        run: npm run truffle test
