name: Test Contracts

on:
  push:
  workflow_dispatch:

jobs:
  Test-React-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      #   - name: Run truffle compile
      #     run: npm run truffle:compile

      #   - name: Run truffle migrate
      #     run: npm run truffle:migrate --network development

      - name: Run truffle test
        run: npm run truffle:test
